import Head from "next/head";
import Home from "../components/home";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Fiber</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter;700&display=swap"
        />
      </Head>
      <Home />
    </div>
  );
}
